Ndlano/issues#126 dynamic doc
NDLANO/api-documentation pull request #2
Opened 2016-12-12 08:47 UTC by kstigen

2016-12-12 11:27 UTC, oyvinmar requested changes
Kanskje oppdatere README også?

2016-12-12 11:27 UTC, oyvinmar commented on src/app.js
> +  fetchAndTransformApis()
Her kan du kalle `fetchApis().then...` direkte. Trenger ikke kalle `fetchAndTransformApis`

2016-12-12 11:27 UTC, oyvinmar commented on src/app.js
> +  const lang = 'nb';
Lang trenger vel ikke å være konfigurerbar. Kan sette direkte i htmlTemplate?

2016-12-12 11:27 UTC, oyvinmar commented on src/app.js
> +    .then((article) => {
`article` -> `apiList` eventuelt `data`

2016-12-12 11:27 UTC, oyvinmar commented on src/utils/htmlTemplates.js
> + export const apiList = (lang, json) => {
`apiList` -> `apiListTemplate`?

2016-12-12 11:27 UTC, oyvinmar commented on package.json
> +    "test": "jest",
Hva med å konfigurere travis ci til å kjøre lint og test scriptene?

2016-12-12 11:55 UTC, chrpeter commented on src/public/css/api-documentation.css
> +    margin-right: auto;
Isteden for margin left og right tror jeg 
`margin: 0 auto`
skal fungere

2016-12-12 12:00 UTC, chrpeter commented on src/public/css/api-documentation.css
> +    margin-bottom: 1em;
`margin: 1em 0 1em 10px` (margin: top right bottom left) isteden for margin left, right og top.

2016-12-12 12:01 UTC, chrpeter commented on src/public/css/api-documentation.css
> +    padding-bottom: 5px;
padding: 5px 0 5px 10px (Samme prinsipp som på linje 47)

2016-12-12 12:02 UTC, chrpeter commented on src/public/css/api-documentation.css
> +    display: block;
Content er vel en div? Da er vel block default?

2016-12-12 12:05 UTC, chrpeter commented on src/utils/errorHelpers.js
> +  return { status, message, description, stacktrace: error.stack };
Vil ikke `return {status, message, description, stacktrace: isProduction ? '' : error.stack }` også fungere? Vet ikke om det er penere dog.

2016-12-13 08:42 UTC, kstigen commented on package.json
> +    "test": "jest",
Da må jeg jo nesten ha en test som kan kjøres også da 😉

2016-12-13 10:54 UTC, oyvinmar approved these changes

2016-12-13 12:53 UTC, merged